; -----------------------------------------------------------------------
; Template source file generated by piklab
    #include <p16f690.inc>

; -----------------------------------------------------------------------
; Configuration bits: adapt to your setup and needs
    __CONFIG _INTOSCIO & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOR_ON & _IESO_ON & _FCMEN_ON

; -----------------------------------------------------------------------
; Változó értékadás
INT_VAR UDATA_SHR
w_saved      RES 1 ; variable used for context saving
status_saved RES 1 ; variable used for context saving
pclath_saved RES 1 ; variable used for context saving

var1         RES 1 ; példa változó


; RA2	IN+PU	^bump opto sensor
; RA4	IN+PU	^button
; RC0	OUT	bump opto LED
; RC1	OUT	LED
; RC2	OUT	lamp

; RC4	OUT	MOTOR orange
; RC5	OUT	MOTOR yellow
; RC6	OUT	MOTOR brown
; RC7	OUT	MOTOR black




; -----------------------------------------------------------------------
; reset vector
STARTUP CODE 0x000
    nop                    ; needed for ICD2 debugging
    movlw   high start     ; felső bájt betöltés a start cimkénél
    movwf   PCLATH         ; PCLATH induló érték
    goto    start          ; menj a start kódra

; megszakítás vektor
INT_VECTOR CODE 0x004
    goto    interrupt      ; menj a megszakítás start kódra

; relocatable code
PROG CODE
interrupt
    movwf   w_saved        ; környezet mentés
    swapf   STATUS,w
    movwf   status_saved
    movf    PCLATH,w       ; only required if using more than first page
    movwf   pclath_saved
    clrf    PCLATH
    ; << megszakítási kód helye >>
    movf    pclath_saved,w ; környezet visszatöltése
    movwf   PCLATH
    swapf   status_saved,w
    movwf   STATUS
    swapf   w_saved,f
    swapf   w_saved,w
    retfie

start
    ; << Fő kód helye >>
    movlw	b'00000010'		; motor off, opto off, LED on
    movwf	PORTC
    bsf		STATUS,RP1
    clrf	ANSEL			; all inputs are digital
    clrf	ANSELH
    bcf		WPUB,4			; disable pull-up on RB4 open drain pin 
    bcf		STATUS,RP1
    bsf		STATUS,RP0
    movlw	b'00001000'		; define 6 outputs on PORTC
    movwf	TRISC
    bcf		OPTION_REG,NOT_RABPU	; global enable pull-ups
    bcf		STATUS,RP0
waitForButton
    btfsc	PORTA,4
    goto	waitForButton
    bsf		PORTC,2
    
    
    
    
    
    
    
    
    goto    $              ; örökké körbe

END
